services:
  postgres:
    image: postgres:16-alpine
    container_name: bootcamp-treinos-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bootcamp-treinos-api
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bootcamp-network

  api:
    build:
      context: .
      target: production
    container_name: bootcamp-treinos-api
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/bootcamp-treinos-api?schema=public
      - NODE_ENV=production
      - API_BASE_URL=http://localhost:8080
      - WEB_APP_BASE_URL=http://localhost:3000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - bootcamp-network

  web:
    build:
      context: ../bootcamp-treinos-frontend
      target: production
    container_name: bootcamp-treinos-web
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
      - NODE_ENV=production
    depends_on:
      - api
    networks:
      - bootcamp-network

networks:
  bootcamp-network:
    driver: bridge

volumes:
  postgres_data:
